apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodehubaz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodehubaz
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: nodehubaz
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: nodehubaz
        image: nodehubacr.azurecr.io/nodehubaz:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m